<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fal_gallery"
 *
 * Auto generated by Extension Builder 2014-08-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'FAL Gallery',
    'description' => 'Easy to use gallery with separate single- , category- and listview.',
    'category' => 'plugin',
    'author' => 'Oliver Eglseder',
    'author_email' => 'php@vxvr.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.2',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-8.5.1',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
